version: '2'

services:

    # APP

    nginx:
        build: docker/nginx
        volumes_from:
            - php
        links:
            - php

    php:
        build: docker/php
        volumes:
            - "./:/symfony"
        links:
            - mysql

    mysql:
        build: docker/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
        volumes:
            - "mysql:/var/lib/mysql"

volumes:
  mysql: ~
