version: '2'

services:

    # APP

    nginx:
        build: docker/nginx
        volumes:
            - "./:/symfony"
        links:
            - php

    php:
        build: docker/php
        volumes:
            - "./:/symfony"
        links:
            - mysql

    mysql:
        build: docker/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=root"

